### ISSUE TITLE
Arango db field casing issue with linq queries

### ISSUE THREAD

**Issue by adamlubek** [ra0o0f/arangoclient.net#39]
hey, first of all, thanks for cool library :) 

Down to business: in arango, I've got Person collection with last name fields (notice second object's field starts with lower case):
[{"LastName":"a"},{"lastName":"b"},{"LastName":"c"}]

In C#, I've got Person class with LastName field.

    public class Person
    {
        public string LastName;
    }

Now, db.Query<Person>().ToList() returns all 3 objects with LastName properly initialized with respective values. However, linq query db.Query<Person>().Where(e => AQL.Contains(e.LastName, "b")).ToList() doesn't return anything. I'm guessing this is not intentional?

**Comment by ra0o0f** [comment]
the reason that `db.Query().ToList()` returns the `lastName`(with the lower `l`) member is because json.net also `deserialize` objects that are camelcased(in your case `lastName` is camelcase of `LastName`). but this behavior is not at serializing objects( `AQL.Contains(e.LastName, "b")` will translate to aql syntax `contains(e.LastName,"b")` ).

but `lastName` & `LastName` are two different document members for the ArangoDB database. you could have both of them in an object. did you load `Person` collection with import tools? if yes try to validate the member names before inserting them(.net client also has a method for import, `db.Advanced.BulkImport` which is not in nuget package yet)

also there are helper methods in .net client that you can override member name resolving

```c#
                sharedSetting.Collection.ChangeCollectionPropertyForType<Person>(x =>
                {
                    // will resolve all collection members name from PascalCase(c#) to camelcase(ArangoDB)
                    x.Naming = NamingConvention.ToCamelCase;
                });

                sharedSetting.Collection.ChangeDocumentPropertyForType<Person>(x => x.LastName, (p) =>
                {
                    // set the name for just one member
                    p.PropertyName = "lastName";

                    // naming convection for just one member
                    p.Naming = NamingConvention.ToCamelCase;
                });
```

**Comment by adamlubek** [comment]
thanks for prompt and detailed response. However, I hope that you see why I find this confusing. From my perspective it would be better if this behavior was more consistent i.e. either arango lastName wouldn't be mapped to LastName in C# while using db.Query<Person>().ToList() or if field content was included while using db.Query().Where(e => AQL.Contains(e.LastName, "b")).ToList()

**Comment by ra0o0f** [comment]
you're right, the resolving names should be consistent either in serializing/serializing, i wont close the issue for now.

**Comment by ra0o0f** [comment]
@adamlubek about consistent member name resolving, json.net behaves `First attempts to get an exact case match of propertyName and then a case insensitive match` according to http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Serialization_JsonPropertyCollection_GetClosestMatchProperty.htm
